import { useState } from "react";
import Head from "next/head";
import { toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const ForgotPassword = () => {
  const [focusedInput, setFocusedInput] = useState(null);
  const [email, setEmail] = useState("");

  const forgotPassword = async () => {
    try {
      // Send a request to your "Reset Password" API route
      const response = await fetch("/api/auth/forgotpassword", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          email,
        }),
      });

      if (response.ok) {
        const data = await response.json();
        // Password reset successful, you can redirect the user to a success page
        toast.success(data.message);
      } else {
        // Handle password reset error, e.g., display an error message to the user
        toast.error("Password reset failed");
      }
    } catch (error) {
      console.error("An error occurred:", error);
    }
  };

  const handleInputClick = (inputName) => {
    setFocusedInput(inputName);
  };
  return (
    <div>
      <Head>
        <title>Forgot Account</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-center px-8 ">
        <h1 className="font-futura text-[30px] font-semibold md:text-[48px] text-light mt-[140px] ">
          Forgot Password
        </h1>

        <div className="font-opensans mx-auto md:max-w-[478px] w-auto mt-[44px]">
          <div className="relative">
            <input
              type="email"
              placeholder=""
              value={email}
              className={`focus:outline-none w-[100%] border border-solid px-[18px] py-[18px] ${
                focusedInput === "email"
                  ? "border-dark border-[1.5px]"
                  : "border-gray-300 "
              }`}
              onClick={() => handleInputClick("email")}
              onChange={(e) => setEmail(e.target.value)}
            />
            <label
              className={`absolute left-4 text-[14px] text-[#9b9191] top-4 transition-all duration-300 ${
                focusedInput === "email" || email
                  ? "translate-y-[-125%] text-[12px] bg-white"
                  : ""
              }`}
            >
              E-mail
            </label>
          </div>
          <button
            onClick={forgotPassword}
            className="mt-[24px]  text-[12px] md:text-[14px] font-semibold bg-dark text-white px-[0px] tracking-[1.5px] py-[18px] w-full"
          >
            Forgot Password
          </button>
        </div>
      </div>
    </div>
  );
};

export default ForgotPassword;
