import Head from "next/head";
import Link from "next/link";
import React, { useState } from "react";


const Login = () => {
    const [email, setEmail] = useState("");
    const [password, setPassword] = useState("");
    const [focusedInput, setFocusedInput] = useState(null);
  
    const handleInputClick = (inputName) => {
      setFocusedInput(inputName);
    };
  return (
    <div>
      <Head>
        <title>Account</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mx-auto text-center px-8 md:px-0">
        <div>
          <h1 className="font-futura text-[30px] md:text-[48px] text-light mt-[140px] ">
            LOGIN
          </h1>
          <p className="mt-[14px] text-[14px] text-[#2E2E2E] font-opensans md:text-[15px]">
            Please enter your e-mail and password:
          </p>
        </div>
        <form className="font-opensans mt-[44px]">
          <div className="mt-4 relative">
            <input
              type="email"
              placeholder=" "
              className={`focus:outline-none w-[100%] border border-solid px-[18px] py-[18px] ${
                focusedInput === "email"
                  ? "border-dark border-[1.5px]"
                  : "border-gray-300 "
              }`}
              onClick={() => handleInputClick("email")}
              onChange={(e) => setEmail(e.target.value)}
            />
            <label
              htmlFor="email"
              className={`absolute left-4 text-[14px] text-[#9b9191] top-4 transition-all duration-300 ${
                focusedInput === "email" || email
                  ? "translate-y-[-125%] text-[12px] bg-white"
                  : ""
              }`}
            >
              Email
            </label>
          </div>
          <div className="mt-4 relative">
            <input
              type="password"
              placeholder=" "
              className={`focus:outline-none w-[100%] border border-solid px-[18px] py-[18px] ${
                focusedInput === "password"
                  ? "border-dark border-[1.5px]"
                  : "border-gray-300 "
              }`}
              onClick={() => handleInputClick("password")}
              onChange={(e) => setPassword(e.target.value)}
            />
            <label
              htmlFor="password"
              className={`absolute left-4 text-[14px] top-4 text-[#9b9191] transition-all duration-300 ${
                focusedInput === "password" || password
                  ? "translate-y-[-125%] text-[12px] bg-white"
                  : ""
              }`}
            >
              Password
            </label>
          </div>
          <button
            className="mt-[24px]  text-[12px] md:text-[14px] font-semibold bg-dark text-white px-[0px] tracking-[1.5px] py-[18px] w-full"
          >
            LOGIN
          </button>
        </form>
        <p className="mt-[14px] text-[14px]  text-[#2E2E2E] font-opensans md:text-[15px]">
          New customer? <Link className="underline text-primary" href="/authentication/Register">Create an account</Link>
        </p>
      </div>
    </div>
  )
}

export default Login