import Head from "next/head";
import Link from "next/link";
import React, { useState } from "react";

const Register = () => {
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [phone, setPhone] = useState("");
  const [password, setPassword] = useState("");
  const [focusedInput, setFocusedInput] = useState(null);

  const handleInputClick = (inputName) => {
    setFocusedInput(inputName);
  };

  return (
    <div>
      <Head>
        <title>Create Account</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mx-auto text-center px-8 md:px-0">
        <div>
          <h1 className="font-futura text-[30px] md:text-[48px] text-light mt-[140px] ">
            REGISTER
          </h1>
          <p className="mt-[14px] text-[14px] text-[#2E2E2E] font-opensans md:text-[15px]">
            Please fill in the fields below:
          </p>
        </div>
        <form className="font-opensans mt-[44px]">
          <div className="w-full relative">
            <input
              type="text"
              placeholder=" "
              className={`focus:outline-none w-[100%] border border-solid px-[18px] py-[18px] ${
                focusedInput === "name"
                  ? "border-dark border-[1.5px]"
                  : "border-gray-300 "
              }`}
              onClick={() => handleInputClick("name")}
              onChange={(e) => setName(e.target.value)}
            />
            <label
              htmlFor="name"
              className={`absolute left-4 text-[14px] text-[#9b9191] top-4 transition-all duration-300 ${
                focusedInput === "name" || name
                  ? "translate-y-[-125%] text-[12px] bg-white"
                  : ""
              }`}
            >
              Name
            </label>
          </div>
          <div className="mt-4 relative">
            <input
              type="email"
              placeholder=" "
              className={`focus:outline-none w-[100%] border border-solid px-[18px] py-[18px] ${
                focusedInput === "email"
                  ? "border-dark border-[1.5px]"
                  : "border-gray-300 "
              }`}
              onClick={() => handleInputClick("email")}
              onChange={(e) => setEmail(e.target.value)}
            />
            <label
              htmlFor="email"
              className={`absolute left-4 text-[14px] text-[#9b9191] top-4 transition-all duration-300 ${
                focusedInput === "email" || email
                  ? "translate-y-[-125%] text-[12px] bg-white"
                  : ""
              }`}
            >
              Email
            </label>
          </div>
          <div className="mt-4 relative">
            <input
              type="number"
              placeholder=" "
              className={`focus:outline-none w-[100%] border border-solid px-[18px] py-[18px] ${
                focusedInput === "phone"
                  ? "border-dark border-[1.5px]"
                  : "border-gray-300 "
              }`}
              onClick={() => handleInputClick("phone")}
              onChange={(e) => setPhone(e.target.value)}
            />
            <label
              htmlFor="phone"
              className={`absolute left-4 text-[14px] text-[#9b9191] top-4 transition-all duration-300 ${
                focusedInput === "phone" || phone
                  ? "translate-y-[-125%] text-[12px] bg-white"
                  : ""
              }`}
            >
              Phone No
            </label>
          </div>
          <div className="mt-4 relative">
            <input
              type="password"
              placeholder=" "
              className={`focus:outline-none w-[100%] border border-solid px-[18px] py-[18px] ${
                focusedInput === "password"
                  ? "border-dark border-[1.5px]"
                  : "border-gray-300 "
              }`}
              onClick={() => handleInputClick("password")}
              onChange={(e) => setPassword(e.target.value)}
            />
            <label
              htmlFor="password"
              className={`absolute left-4 text-[14px] top-4 text-[#9b9191] transition-all duration-300 ${
                focusedInput === "password" || password
                  ? "translate-y-[-125%] text-[12px] bg-white"
                  : ""
              }`}
            >
              Password
            </label>
          </div>
          <button
            className="mt-[24px]  text-[12px] md:text-[14px] font-semibold bg-dark text-white px-[0px] tracking-[1.5px] py-[18px] w-full"
          >
            CREATE ACCOUNT
          </button>
        </form>
        <p className="mt-[14px] text-[14px]  text-[#2E2E2E] font-opensans md:text-[15px]">
          Already have an account? <Link className="underline text-primary" href="/authentication/Login">Login</Link>
        </p>
      </div>
    </div>
  );
};

export default Register;
