import { useState } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import { toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const ResetPasswordPage = () => {
  const router = useRouter();
  const [newPassword, setNewPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [focusedInput, setFocusedInput] = useState(null);

  const resetPassword = async () => {
    try {
      if (newPassword !== confirmPassword) {
        // Password and confirmation password do not match
        toast.error("Passwords do not match");
        return;
      }
      // Send a request to your "Reset Password" API route
      const response = await fetch("/api/auth/resetpassword", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          newPassword,
          resetToken: router.query.token, // Get the reset token from the URL
        }),
      });

      if (response.ok) {
        // Password reset successful, you can redirect the user to a success page
        toast.success("Password reset successful");
        router.push("/");
      } else {
        // Handle password reset error, e.g., display an error message to the user
        toast.error("Password reset failed");
      }
    } catch (error) {
      console.error("An error occurred:", error);
    }
  };

  const handleInputClick = (inputName) => {
    setFocusedInput(inputName);
  };

  return (
    <div>
      <Head>
        <title>Reset Account</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-center ">
        <h1 className="font-futura text-[30px] font-semibold md:text-[48px] text-light mt-[140px] ">
          Reset Password
        </h1>
        <form
          onSubmit={resetPassword}
          className="font-opensans mx-auto md:max-w-[478px] w-auto mt-[44px]"
        >
          <div className="relative">
            <input
              type="password"
              placeholder=""
              value={newPassword}
              className={`focus:outline-none w-[100%] border border-solid px-[18px] py-[18px] ${
                focusedInput === "newPassword"
                  ? "border-dark border-[1.5px]"
                  : "border-gray-300 "
              }`}
              onClick={() => handleInputClick("newPassword")}
              onChange={(e) => setNewPassword(e.target.value)}
            />
            <label
              htmlFor="phone"
              className={`absolute left-4 text-[14px] text-[#9b9191] top-4 transition-all duration-300 ${
                focusedInput === "newPassword" || newPassword
                  ? "translate-y-[-125%] text-[12px] bg-white"
                  : ""
              }`}
            >
              New Password
            </label>
          </div>
          <div className="mt-4 relative">
            <input
              type="password"
              placeholder=""
              value={confirmPassword}
              className={`focus:outline-none w-[100%] border border-solid px-[18px] py-[18px] ${
                focusedInput === "confirmPassword"
                  ? "border-dark border-[1.5px]"
                  : "border-gray-300 "
              }`}
              onClick={() => handleInputClick("confirmPassword")}
              onChange={(e) => setConfirmPassword(e.target.value)}
            />
            <label
              className={`absolute left-4 text-[14px] text-[#9b9191] top-4 transition-all duration-300 ${
                focusedInput === "confirmPassword" || confirmPassword
                  ? "translate-y-[-125%] text-[12px] bg-white"
                  : ""
              }`}
            >
              Confirm Password
            </label>
          </div>
          <button
            type="submit"
            className="mt-[24px]  text-[12px] md:text-[14px] font-semibold bg-dark text-white px-[0px] tracking-[1.5px] py-[18px] w-full"
          >
            Reset Password
          </button>
        </form>
      </div>
    </div>
  );
};

export default ResetPasswordPage;
