import useProductCategoryStore from "@/store/pcategory/pStore";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import { toast } from "react-toastify";

const Category = () => {
  const createCategory = useProductCategoryStore(
    (state) => state.createCategory
  );

  const [categoryName, setCategoryName] = useState("");

  const handleCategoryNameChange = (e) => {
    setCategoryName(e.target.value);
  };

  const addCategory = (e) => {
    e.preventDefault();
    if (categoryName.trim() === "") {
      // Handle validation or show an error message.
      return;
    }

    createCategory({ title: categoryName });
    toast.success("Product category added successfully");
    setCategoryName(""); // Clear the category name input field
  };
  return (
    <div>
      <Head>
        <title>Mma-Inspire Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full">
        <h2 className="text-center text-[25px] font-opensans mt-12">
          Add Product Category
        </h2>
        <form
          onSubmit={addCategory}
          className="flex mb-4 flex-col mx-auto gap-8 mt-6 justify-center"
        >
          <input
            type="text"
            placeholder="Category Name"
            value={categoryName}
            onChange={handleCategoryNameChange}
            className="px-4 py-4 focus:outline-none border border-dark border-solid"
          />
          <button
            type="submit"
            className="mt-[24px] text-[12px] md:text-[14px] font-semibold bg-dark text-white px-[0px] tracking-[1.5px] py-[18px]"
          >
            Add Category
          </button>
        </form>
      </div>
    </div>
  );
};

export default Category;
