import useColorStore from "@/store/color/colorStore";
import React, { useEffect } from "react";
import { getColorFromLocalStorage } from "@/utils/Localstorage";
import { toast } from 'react-toastify';
import Head from "next/head";

const Colorlist = () => {
  const colorStore = useColorStore(); // Get the color store
  const getColors = useColorStore((state) => state.getColors);

  const handleDeleteColor = () => {
    if (window.confirm("Are you sure you want to delete this color?")) {
      // Update the DELETE request to include the color ID in the URL
      const parsedColors = getColorFromLocalStorage();
      const id = parsedColors?._id;
      if (!id) {
        throw new Error("User ID not found in localStorage");
      }
      fetch(`/api/product/color?id=${id}`, {
        method: "DELETE",
      })
        .then((response) => {
          if (response.ok) {
            // Handle successful deletion
            toast.success("Color deleted successfully");
            // Refresh the colors list by calling getColors
            getColors();
          } else {
            // Handle errors (e.g., show an error message)
            console.error("Error deleting color:", response.statusText);
          }
        })
        .catch((error) => {
          // Handle any fetch-related errors
          console.error("Fetch error:", error);
        });
    }
  };

  useEffect(() => {
    // Fetch the colors when the component mounts
    colorStore.getColors();
  }, []);

  useEffect(() => {
    // Fetch the list of colors when the component loads
    getColors();
  }, [getColors]);


  return (
    <div className="mt-12">
        <Head>
        <title>Mma-Inspire Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2 className="text-center text-[25px] font-futura">Colors</h2>
      <table className="min-w-full divide-y divide-gray-200">
        <thead>
          <tr>
            <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
              Name
            </th>
            <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
              Hex
            </th>
            <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
              Actions
            </th>
          </tr>
        </thead>
        <tbody className="bg-white divide-y divide-gray-200">
          {colorStore.colors.map((color) => (
            <tr key={color.id}>
              <td className="px-6 py-4 whitespace-nowrap">{color.title}</td>
              <td className="px-6 py-4 whitespace-nowrap">
                <span
                  className="bg-gray-200 text-gray-800 rounded-full px-2 py-1 text-xs font-semibold"
                  style={{ backgroundColor: color.hex }}
                >
                  {color.hex}
                </span>
              </td>
              <td className="px-6 py-4 whitespace-nowrap">
                <button
                  onClick={() => handleDeleteColor(color.id)}
                  className="text-red-600 hover:text-red-900"
                >
                  Delete
                </button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};

export default Colorlist;
