import useColorStore from "@/store/color/colorStore";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import { toast } from "react-toastify";

const Color = () => {
  const createColor = useColorStore((state) => state.createColor);
  const getColors = useColorStore((state) => state.getColors);

  const [colorName, setColorName] = useState("");
  const [colorHex, setColorHex] = useState("#000000");

  const handleColorNameChange = (e) => {
    setColorName(e.target.value);
  };

  const handleColorHexChange = (e) => {
    setColorHex(e.target.value);
  };

  const addColor = (e) => {
    e.preventDefault();
    if (colorName.trim() === "") {
      // Handle validation or show an error message.
      return;
    }

    createColor({ title: colorName, hex: colorHex });
    toast.success("Color added successfully");
    setColorName(""); // Clear the name input field
    setColorHex("#000000"); // Reset the color to default
  };

  useEffect(() => {
    // Fetch the list of colors when the component loads
    getColors();
  }, [getColors]);

  return (
    <div className="w-full">
        <Head>
        <title>Mma-Inspire Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2 className="text-center text-[25px] font-opensans mt-12">Add Color</h2>
      <form
        onSubmit={addColor}
        className="flex mb-4 flex-col mx-auto gap-8 mt-6 justify-center"
      >
        <input
          type="text"
          placeholder="Color Name"
          value={colorName}
          onChange={handleColorNameChange}
          className=" px-4 py-4 focus:outline-none  border border-dark border-solid"
        />
        <input
          type="color"
          value={colorHex}
          onChange={handleColorHexChange}
          className="w-full h-[70px]"
        />
        <button
          type="submit"
          className="mt-[24px]  text-[12px] md:text-[14px] font-semibold bg-dark text-white px-[0px] tracking-[1.5px] py-[18px]"
        >
          Add Color
        </button>
      </form>
    </div>
  );
};

export default Color;
