import ImageUpload from "@/components/Imageupload";
import Head from "next/head";



export default function Home() {
  return (
   <div>
      <Head>
        <title>Mma-Inspire</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ImageUpload/>
   </div>
  )
}
