import Head from "next/head";
import React from "react";
import Navbar from "./Homepage/Navbar";
import { useAuth } from "@/utils/auth";


const Homelayout = ({children}) => {
  const {user } = useAuth();
  return (
    <div >
      <Head>
        <title>Mma-Inspire</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div >
        <h1 className="text-center mx-auto text-[12px] md:text-[16px] text-dark font-opensans bg-secondary py-3 md:py-5">
          WORLDWIDE SHIPPING AVAILABLE
        </h1>
      </div>
      <Navbar session={[user]}/>
      <main className="lg:mt-[9rem]">{children}</main>
    </div>
  );
};

export default Homelayout;
