import ImageUpload from '@/components/Imageupload';
import Head from 'next/head';

function ImageUploadPage() {
  return (
    <div>
        <Head>
        <title>Mma-Inspire Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='text-center font-futura font-semibold text-[18px] mt-12'>Image Upload - Step 2</h1>
      <ImageUpload />
    </div>
  );
}

export default ImageUploadPage;
