import Head from 'next/head'
import React from 'react'

const Orders = () => {
  return (
    <div>
        <Head>
        <title>Mma-Inspire Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}

export default Orders